Store/StoreApp/Areas/Admin/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Mvc;

namespace StoreApp.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class CategoryController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Store/StoreApp/Areas/Admin/Controllers/DashboardController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ActionConstraints;

namespace StoreApp.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class DashboardController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Store/StoreApp/Areas/Admin/Controllers/ProductController.cs
using Entities.Models;
using Microsoft.AspNetCore.Mvc;
using Services.Contracts;

namespace StoreApp.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class ProductController : Controller
    {
        private readonly IServiceManager _manager;

        public ProductController(IServiceManager manager)
        {
            _manager = manager;
        }

        public IActionResult Index()
        {
            var model = _manager.ProductService.GetAllProducts(false);

            return View(model);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([FromForm] Product product)
        {

            return View();
        }
    }
}

Store/StoreApp/Components/CategoriesMenuViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Services.Contracts;

namespace StoreApp.Components
{
    public class CategoriesMenuViewComponent : ViewComponent
    {
        private readonly IServiceManager _manager;

        public CategoriesMenuViewComponent(IServiceManager manager)
        {
            _manager = manager;
        }

        public IViewComponentResult Invoke()
        {
            var categories = _manager.CategoryService.GetCategories(false);
            return View(categories);
        }
    }
}

Store/StoreApp/Components/ProductSummaryViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Repositories;
using Services.Contracts;

namespace StoreApp.Components
{
    public class ProductSummaryViewComponent : ViewComponent
    {
        private readonly IServiceManager _manager;

        public ProductSummaryViewComponent(IServiceManager manager)
        {
            _manager = manager;
        }

        public string Invoke()
        {
            return _manager.ProductService.GetAllProducts(false).Count().ToString();
        }
    }
}

Store/StoreApp/Controllers/CategoryController.cs
using Entities.Models;
using Microsoft.AspNetCore.Mvc;
using Repositories.Contracts;
using Services.Contracts;

namespace StoreApp.Controllers
{
    public class CategoryController : Controller
    {
        private IServiceManager _manager;

        public CategoryController(IServiceManager manager)
        {
            _manager = manager;
        }

        public IActionResult Index()
        {
            var model = _manager.CategoryService.GetCategories(false);
            return View(model);
        }

    }
}

Store/StoreApp/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace AppStore.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Privacy()
        {
            return View();
        }
    }
}

Store/StoreApp/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Entities.Models;
using Repositories;
using Repositories.Contracts;
using Services.Contracts;


namespace StoreApp.Controllers
{
    public class ProductController : Controller
    {
        private readonly IServiceManager _manager;

        public ProductController(IServiceManager manager)
        {
            _manager = manager;
        }


        public IActionResult Index()
        {

            var model = _manager.ProductService.GetAllProducts(false);
            return View(model);
        }

        public IActionResult Get([FromRoute(Name = "id")]int id)
        {

            var model = _manager.ProductService.GetOneProduct(id, false);
            return View(model);
        }
    }
}

Store/StoreApp/Areas/Admin/Views/Category/Index.cshtml
@{
    Layout = "_Layout";
}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>BTK Akademi </title>

</head>

<body>
    <h3>Category Index </h3>

</body>

</html>

Store/StoreApp/Areas/Admin/Views/Product/Create.cshtml
@model Product

<div class="text-center">
    <div class="display-6">Create</div>
</div>

<form method="post" asp-action="Create">
    <div class="form-group my-3">
        <label asp-for="ProductName">Product Name</label>
        <input asp-for="ProductName" class="form-control" placeholder="Product Name" />
    </div>
    <div class="form-group my-3">
        <label asp-for="Price">Product Price</label>
        <input asp-for="Price" class="form-control" placeholder="Product Price" />
    </div>

    <div class="form-group my-3">
        <div class="btn-group">
            <button class="btn btn-primary" type="submit">
                <i class="fa fa-save"></i>
                Save
            </button>
            <a asp-action="Index" class="btn btn-outline-primary mx-2">
                <i class="fa fa-list"></i>

                Products
            </a>
        </div>


    </div>
</form>

Store/StoreApp/Areas/Admin/Views/Product/Index.cshtml
@model IEnumerable<Product>

<div class="text-center">
    <div class="display-6">Products</div>
    <div class="d-flex justify-content-end my-3">
        <a class="btn btn-outline-success" asp-action="Create">
            <i class="fa fa-plus"></i>

            Create
        </a>
    </div>
    <table class="table table-striped table-hover">
        <thead>
            <tr>
                <th>Id</th>
                <th>Product Name</th>
                <th>Price</th>
                <th>Operations</th>
            </tr>
        </thead>
        <tbody>
            @foreach (Product prd in Model)
            {
                <tr>
                    <td>@prd.ProductId</td>
                    <td>@prd.ProductName</td>
                    <td>@prd.Price</td>
                    <td>.</td>
                </tr>
            }
        </tbody>
    </table>

</div>

Store/StoreApp/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>BTK Akademi </title>
    <link asp-append-version="true" rel="stylesheet" href="~/lib/bootstrap/css/bootstrap.min.css" />
    <link asp-append-version="true" rel="stylesheet" href="~/css/site.css" />
    <link asp-append-version="true" rel="stylesheet" href="~/lib/font-awesome/css/all.css" />
</head>

<body>
    <header>
        <partial name="_Navbar" />
        @RenderSection("Header", false)
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <script asp-append-version="true" src="~/lib/bootstrap/js/bootstrap.bundle.min.js"></script>

    <script asp-append-version="true" src="~/lib/jquery/jquery.min.js"></script>
    <script asp-append-version="true" src="~/js/site.js"></script>
    <script asp-append-version="true" src="~/lib/font-awesome/js/all.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
    <footer>
        Footer
        @RenderSection("Footer", false)
    </footer>
</body>

</html>

Store/StoreApp/Views/Product/Get.cshtml
@model Product


<h6>@Model.ProductName</h6>
<h6>@Model.Price</h6>
<div class="btn-group">
    <a class="btn btn-primary " asp-controller="Home" asp-action="Index">
        <i class="fa-solid fa-house mx-2"></i>Home</a>
    
    <a class="btn btn-outline-primary  mx-4" asp-controller="Products" asp-action="Index">
        <i class="fa-solid fa-list mx-2"></i>
        Products</a>

</div>


@section Header {
    <div>Header for only Get</div>
}

Store/StoreApp/Views/Product/Index.cshtml
@model IEnumerable<Product>


<div class="row">
    <div class="col-md-3">
        @await Component.InvokeAsync("CategoriesMenu")
    </div>
    <div class="col-md-9">
        <div class="row my-4">

            @foreach (Product product in Model)
            {
                <partial name="_ProductCard" model="@product" />
            }
        </div>
    </div>

</div>

@section Footer {
    <div>Only for Index footer</div>
}

Store/StoreApp/Views/Product/_ProductCard.cshtml
@model Product

<div class="col-md-4 my-2">
    <div class="card" style="width: 18rem;">
        <img class="card-img-top" src="/images/default.jpg" alt="Card image cap">
        <div class="card-body">
            <h5 class="card-title"> @Model.ProductName</h5>
            <p class="card-text">@Model.Price.ToString("c")</p>
            <a asp-action="Get" asp-route-id="@Model.ProductId" class="btn btn-primary">
                <i class="fa-solid fa-arrow-right"></i>
                Get Details</a>
        </div>
    </div>
</div>

Store/StoreApp/Views/Shared/Components/CategoriesMenu/Default.cshtml
@model IEnumerable<Category>


<div>
    <ul class="list-group m-4">
        @foreach (var cat in Model)
        {
            <li class="list-group-item">
            @cat.CategoryName
        </li>
        }
    </ul>
</div>

Store/StoreApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>BTK Akademi </title>
    <link asp-append-version="true" rel="stylesheet" href="~/lib/bootstrap/css/bootstrap.min.css" />
    <link asp-append-version="true" rel="stylesheet" href="~/css/site.css" />
    <link asp-append-version="true" rel="stylesheet" href="~/lib/font-awesome/css/all.css" />
</head>

<body>
    <header>
        <partial name="_Navbar" />
        @RenderSection("Header", false)
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <script asp-append-version="true" src="~/lib/bootstrap/js/bootstrap.bundle.min.js"></script>

    <script asp-append-version="true" src="~/lib/jquery/jquery.min.js"></script>
    <script asp-append-version="true" src="~/js/site.js"></script>
    <script asp-append-version="true" src="~/lib/font-awesome/js/all.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
    <footer>
        Footer
        @RenderSection("Footer", false)
    </footer>
</body>

</html>

Store/StoreApp/Views/Shared/_Navbar.cshtml
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <a class="navbar-brand mx-4" href="/">Store App</a>
    <button class="navbar-toggler ml-2" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup"
        aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
            <a class="nav-item nav-link active " asp-controller="Home" asp-action="Index">Home <span
                    class="sr-only">(current)</span></a>
            <a class="nav-item nav-link" asp-controller="Home" asp-action="Privacy">Privacy</a>
            <a class="nav-item nav-link" asp-controller="Product" asp-action="Index">Products(@await Component.InvokeAsync("ProductSummary"))</a>
            <a class="nav-item nav-link" asp-controller="Category" asp-action="Index">Category</a>

        </div>
    </div>
</nav>